tasks
js-tasks-ru/jsbasic-20201022_mehomeisgood pull request #6
Opened 2020-11-09 09:55 UTC by Vlad-IT1

Модуль 3

2020-11-09 10:10 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-11-10 16:04 UTC, koalex requested changes

2020-11-10 16:04 UTC, koalex commented on 2-module/3-task/index.js
> +alert(calculator.sum() );
удали строки 17 и 18 они мешают тестам

2020-11-10 16:04 UTC, koalex commented on 3-module/2-task/index.js
> +alert( filtered );
15 и 17 тоже удали

2020-11-10 17:15 UTC, closed without merging